services:
  - name: Factorio
    service: factorio
    ports: 8555
  - name: Minecraft
    service: minecraft
    ports: 8969 8969
  - name: 7 Days to Die
    service: 7daystodie
    ports: TCP 8082 8083 26900 UDP 26900-26902
  - name: Arma
    service: armaweb
    ports: TCP 8900
  - name: Eco
    service: eco-server
    ports: 8200 8201 8202
  - name: Barotrauma
    service: barotrauma
    ports: TCP 8850-8851
