services:
  - name: Factorio
    service: factorio
    ports: 8555
  - name: Minecraft
    service: minecraftbe
    ports: BOTH 8969
  - name: 7 Days to Die
    service: 7daystodie
    ports: TCP 8082 8083 26900 UDP 26900-26902
  - name: Arma
    service: armaweb
    ports: TCP 8900
  - name: Eco
    service: eco-server
    ports: 8200 8201 8202
  - name: Barotrauma
    service: barotrauma
    ports: TCP 8850-8851
  - name: Valheim
    service: valheim
    ports: TCP 8123
  - name: Core Keeper
    service: corekeeper
    ports: TCP 8234
  - name: Foundry VTT
    service: foundry
    ports: TCP 8120
  - name: Project Zomboid
    service: zomboid
    ports: UDP 8301 8302